import "./globals.css";
import { Inter } from "next/font/google";
import ClientProvider from "./hooks/useClient";
import UserProvider from "./hooks/useUser";
import ProductProvider from "./hooks/useProduct";
import EmployeeProvider from "./hooks/useEmployee";
import SupplierProvider from "./hooks/useSupplier";
import OrderProvider from "./hooks/useOrder";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coffee ERP Crio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ProductProvider>
            <SupplierProvider>
              <OrderProvider>
                <EmployeeProvider>
                  <ClientProvider>
                    {children}
                  </ClientProvider>
                </EmployeeProvider>
              </OrderProvider>
            </SupplierProvider>
          </ProductProvider>
        </UserProvider>
      </body>
    </html>
  );
}
